# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediumautopost < Formula
  desc ""
  homepage "https://github.com/askcloudarchitech/mediumautopost"
  version "0.2.4"

  on_macos do
    url "https://github.com/Darth-Tech/samwise-cli/releases/download/v0.2.4/samwise-cli_0.2.4_darwin_all.tar.gz"
    sha256 "bc971f381769bc23cedc975b0d8765f6fb1f504d35faa03a835cb929b9eaf370"

    def install
      bin.install "samwise-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Darth-Tech/samwise-cli/releases/download/v0.2.4/samwise-cli_0.2.4_linux_amd64.tar.gz"
        sha256 "4e812a53c00cb5ceb1df210b4cfb512eaee33ff4c010b7af08d3107436f851d5"

        def install
          bin.install "samwise-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Darth-Tech/samwise-cli/releases/download/v0.2.4/samwise-cli_0.2.4_linux_arm64.tar.gz"
        sha256 "1f8777451f9e2ca72afc0dd61f45c35129991f533bac7a404a964e0e3e11cc80"

        def install
          bin.install "samwise-cli"
        end
      end
    end
  end
end
