# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SamwiseCli < Formula
  desc ""
  homepage "https://github.com/Darth-Tech/samwise-cli"
  version "0.3.6"

  on_macos do
    url "https://github.com/Darth-Tech/samwise-cli/releases/download/v0.3.6/samwise-cli_0.3.6_darwin_all.tar.gz"
    sha256 "35f1fbf7f7757872dedca9d0a4baac65bc80b4ad1519e26fd18a557f829eaffa"

    def install
      bin.install "samwise-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Darth-Tech/samwise-cli/releases/download/v0.3.6/samwise-cli_0.3.6_linux_amd64.tar.gz"
        sha256 "b0b5e8639356cd38194b6d9cad635686d7a6caf61eadc4ff0e7fff54dbdad355"

        def install
          bin.install "samwise-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Darth-Tech/samwise-cli/releases/download/v0.3.6/samwise-cli_0.3.6_linux_arm64.tar.gz"
        sha256 "21ac93ffdd3142c7159025177d11d1024c6117c6ba70083a9f0be332bc24676f"

        def install
          bin.install "samwise-cli"
        end
      end
    end
  end
end
